-- FoodHub schema
-- Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text unique not null,
  password_hash text not null,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.foods (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  image text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id),
  customer_name text not null,
  phone text not null,
  address text not null,
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Preparing','Out for Delivery','Delivered','Cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  food_id bigint not null references public.foods(id),
  food_name text not null,
  price numeric(10,2) not null,
  quantity integer not null check (quantity > 0)
);

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_id uuid not null references public.users(id),
  sender_role text not null check (sender_role in ('customer','admin')),
  message text not null check (char_length(trim(message)) > 0),
  created_at timestamptz not null default now()
);

create unique index if not exists chats_one_per_user on public.chats(user_id);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_messages_chat_id on public.messages(chat_id);
create index if not exists idx_messages_created_at on public.messages(created_at);

insert into public.foods(name,description,price,image)
select * from (values
  ('Chicken Burger','Juicy chicken burger with fresh vegetables.',220.00,'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800'),
  ('Chicken Pizza','Cheesy chicken pizza with herbs and vegetables.',550.00,'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800'),
  ('Fried Chicken','Crispy fried chicken with a delicious coating.',280.00,'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800'),
  ('Pasta','Creamy pasta prepared with chicken and herbs.',320.00,'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800'),
  ('French Fries','Golden crispy fries with a light seasoning.',150.00,'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800'),
  ('Chocolate Cake','Soft chocolate cake with rich chocolate flavor.',180.00,'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800')
) as seed(name,description,price,image)
where not exists (select 1 from public.foods where public.foods.name=seed.name);
